apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: authentication-prod
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:prod-postgres-password@postgres:5432/authentication_system
  JWT_SECRET: prod-jwt-secret-change-me