apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: authentication-prod
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: prod-postgres-password
  POSTGRES_DB: authentication_system