apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-service
  namespace: authentication-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-service
  template:
    metadata:
      labels:
        app: resource-service
    spec:
      containers:
        - name: resource-service
          image: authentication-system-resource-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: development

            - name: APP_ENV
              value: prod

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET

            - name: JWT_ISSUER
              value: auth-service

            - name: JWT_AUDIENCE
              value: resource-service