apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: prod-auth-service-mapping
  namespace: emissary
spec:
  hostname: "*"
  prefix: /prod/auth/
  rewrite: /
  service: auth-service.authentication-prod:3001