apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: authentication-dev
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/authentication_system
  JWT_SECRET: local-dev-jwt-secret