apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: authentication-dev
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: authentication_system